# Generated by Django 4.1.7 on 2023-03-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admin", "0002_delete_tbl_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=50)),
            ],
        ),
    ]
