# Generated by Django 4.1.7 on 2023-03-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0004_tbl_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_place",
            name="plc_pincode",
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
