# Generated by Django 4.1.7 on 2023-03-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0005_tbl_place_plc_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_place",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Admin.tbl_district",
            ),
        ),
        migrations.AlterField(
            model_name="tbl_place",
            name="plc_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tbl_place",
            name="plc_pincode",
            field=models.IntegerField(null=True),
        ),
    ]
