# Generated by Django 4.1.7 on 2023-03-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0008_tbl_subcategory"),
    ]

    operations = [
        migrations.RemoveField(model_name="tbl_subcategory", name="category",),
        migrations.DeleteModel(name="tbl_Category",),
        migrations.DeleteModel(name="tbl_SubCategory",),
    ]
