# Generated by Django 4.1.7 on 2023-03-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0010_tbl_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_name", models.CharField(max_length=50, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Admin.tbl_category",
                    ),
                ),
            ],
        ),
    ]
