# Generated by Django 4.1.7 on 2023-03-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0004_tbl_sellerreg"),
        ("Admin", "0011_tbl_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Guest.tbl_sellerreg",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Guest.tbl_userreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tbl_complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("status", models.IntegerField(default=0)),
                ("reply", models.CharField(default="Not yet viewed", max_length=1000)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Guest.tbl_sellerreg",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Guest.tbl_userreg",
                    ),
                ),
            ],
        ),
    ]
