# Generated by Django 4.1.7 on 2023-03-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="tbl_Slrproduct",),
    ]
