# Generated by Django 4.1.7 on 2023-03-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Guest", "0004_tbl_sellerreg"),
        ("Admin", "0011_tbl_subcategory"),
        ("Seller", "0002_delete_tbl_slrproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_Slrproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prdct_name", models.CharField(max_length=50)),
                ("prdct_details", models.CharField(max_length=50)),
                ("prdct_rate", models.IntegerField(max_length=50)),
                ("prdct_image", models.FileField(upload_to="sllrprdctimg/")),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Guest.tbl_sellerreg",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Admin.tbl_subcategory",
                    ),
                ),
            ],
        ),
    ]
