# Generated by Django 4.1.7 on 2023-03-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admin", "0011_tbl_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_SellerReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sllrname", models.CharField(max_length=50)),
                ("sllrcontact", models.IntegerField(max_length=50)),
                ("sllremail", models.CharField(max_length=50)),
                ("sllraddress", models.CharField(max_length=50)),
                ("sllrlandmark", models.CharField(max_length=50)),
                ("sllrpassword", models.CharField(max_length=50)),
                ("sllrconformpswd", models.CharField(max_length=50)),
                ("sllrproof", models.FileField(upload_to="sllrprfdocs/")),
                ("sllrphoto", models.FileField(upload_to="sllrphtodocs")),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Admin.tbl_place",
                    ),
                ),
            ],
        ),
    ]
