# Generated by Django 4.1.7 on 2023-03-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0011_tbl_subcategory"),
        ("Guest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_UserReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usrname", models.CharField(max_length=50)),
                ("usrcontact", models.IntegerField(max_length=50)),
                ("usremail", models.CharField(max_length=50)),
                ("usrgender", models.CharField(max_length=50)),
                ("usraddress", models.CharField(max_length=50)),
                ("usrpassword", models.CharField(max_length=50)),
                ("usrconformpswd", models.CharField(max_length=50)),
                ("usrphoto", models.FileField(upload_to="userphtodocs")),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Admin.tbl_place",
                    ),
                ),
            ],
        ),
    ]
