# Generated by Django 4.1.7 on 2023-03-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0002_tbl_userreg"),
    ]

    operations = [
        migrations.DeleteModel(name="tbl_SellerReg",),
    ]
